n = input('\033[1;33;32mDigite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(n)))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um número? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanúmérico? {}'.format(n.isalnum()))
print('Está em maisculas? {}'.format(n.isupper()))
print('Está em minusculas? {}'.format(n.islower()))
print('Está capitalizada? {}'.format(n.istitle()))