l = float(input('Digite a largura da parede: '))
a = float(input('Digite a altura da parede: '))
area = (l*a)
print('Sua parede tem a dimensão de {}x{} e sua área é de {:.2f}m²'.format(l,a,area))
print('Para pintar essa parede você precisará de {:.2f} litros de tinta.'.format((area/2)))