n = str(input('\033[7;30;45mDigite seu nome completo: ')).strip()
print('\033[1;30;2mAnalisando seu nome.....')
print('Seu nome em maiúsculas é {}.'.format(n.upper()))
print('Seu nome em minúsculas é {}.'.format(n.lower()))
print('Seu nome tem {} letras.'.format(len(n)-n.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(n.find(' ')))